# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Technical Review', 'Technical Review'), ('Functional Review', 'Functional Review'), ('Customer Acceptance', 'Customer Acceptance')], max_length=20)),
                ('dependency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileUser')),
            ],
        ),
    ]
